### ISSUE TITLE
404 for git_hook ,  gitea version is 1.8.0

### ISSUE THREAD

**Issue by xuecanlong** [go-gitea/go-sdk#163]
https://godoc.org/code.gitea.io/sdk/gitea#Client.EditRepoGitHook
i use this api to connect my gitea, but it happened in 404
my gitea version is 1.8.0

**Comment by xuecanlong** [comment]
sorry, i find in branch master merged. but, When will it be released?

**Comment by lafriks** [comment]
It will be in 1.9.0
