### ISSUE TITLE
Information necessary for calling func (*Client) CreatePullRequest

### ISSUE THREAD

**Issue by pedrobisp** [go-gitea/go-sdk#164]
When calling ```CreatePullRequest(owner, repo string, opt CreatePullRequestOption)```, I am facing an issue since I do not know how to specify information about the base and head repos, since they are simple strings in the ```CreatePullRequestOption``` struct.

I would expect to be able to specify at least some repo information (such as id, name, owner, etc.) and branch information.

But I do not see how to do it since these fields are simple strings.

Any hints?

**Comment by pedrobisp** [comment]
After digging into the [code.gitea.io/routers/api/v1/repo/](https://github.com/go-gitea/gitea/blob/be666b03eef1e085adc0749837480e0db7f811ad/routers/api/v1/repo/pull.go), I could find out that ```CreatePullRequestOption.Base``` should contain the branch name in the base repo, and ```CreatePullRequestOption.Head``` should contain something like "user:head_branch", or just "head_branch", if pr is coming from the same repo.

Anyways, a little bit more documentation is always nice to have :)

**Comment by lafriks** [comment]
help on documentation is always welcome :)
