### ISSUE TITLE
SDK depends on Gitea

### ISSUE THREAD

**Issue by jonasfranz** [go-gitea/go-sdk#177]
go-sdk depends currently on code.gitea.io/gitea that implicates that all dependencies of gitea are needed to for go-sdk. We should consider fixing this since it will increase the size of binaries of tools using the sdk.

**Comment by lunny** [comment]
In fact, it only depends `code.gitea.io/gitea/modules/structs`, but `go mod` will require all the packages of gitea. Maybe we should put go.mod on `code.gitea.io/gitea/modules/structs` to fix this problem?
