### ISSUE TITLE
Improve lint

### ISSUE THREAD

**Issue by DblK** [go-gitea/go-sdk#3]
Currently we have a [12%](https://goreportcard.com/report/github.com/go-gitea/go-sdk#golint) for go lint.
I suggest to make multiple PR by files to improve this and to raise the percent higher.

**Comment by tboerger** [comment]
And since I also added it to the drone CI run the tests are also failing because of that ;)

**Comment by bkcsoft** [comment]
@xinity do you want this one? otherwise I can take care of it :)

**Comment by lunny** [comment]
I think this is resolved via #12 & #13
